### ISSUE TITLE
title bar, workspace indicator not showing and another problem

### ISSUE THREAD

**Issue by CorePoint** [neeasade/dotfiles#11]
Hey,
really like your setup and i've been using it for some time.

Unfourtunatly i have some problems since the bspwm update.

The title bar and the workspace indicator are not there anymore.
I also hat to change `kill -s 15 $(cat /tmp/panel-pid) 2>/dev/null || LAUNCH_PANEL=false` to `kill -s 15 $(cat /tmp/panel-pid) 2>/dev/null || LAUNCH_PANEL=true`, otherwise the panel won't start.

I made a fresh arch install in virtualbox to see if it's something on my end.

There aren't any errors in the xinit.log.
Are there any more log files i could show you?

Greetings

**Comment by neeasade** [comment]
Oh hello there.

Yes, the panel is broken for perhaps 2 weeks now -- I did not update it on
purpose to give me more incentive to work on it's replacement (
https://github.com/neeasade/lemonade) -- and as for the panel not starting
initially, that is a side effect of a recent re-work of the bspwmrc. You
can still toggle it with panelt or the keybind super + shift + /, I have
not decided how to start it initially yet. I will be taking a more
prioritized look at panel replacement this evening (it's the top item on
meta/README.md)

I appreciate your effort/checking a VM before filing the issue.

Thanks for letting me know,
neeasade

On Thu, Apr 21, 2016 at 9:40 AM, CorePoint <notifications@github.com> wrote:

> Hey,
> really like your setup and i've been using it for some time.
>
> Unfourtunatly i have some problems since the bspwm update.
>
> The title bar and the workspace indicator are not there anymore.
> I also hat to change kill -s 15 $(cat /tmp/panel-pid) 2>/dev/null ||
> LAUNCH_PANEL=false to kill -s 15 $(cat /tmp/panel-pid) 2>/dev/null ||
> LAUNCH_PANEL=true, otherwise the panel won't start.
>
> I made a fresh arch install in virtualbox to see if it's something on my
> end.
>
> There aren't any errors in the xinit.log.
> Are there any more log files i could show you?
>
> Greetings
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/neeasade/dotfiles/issues/11>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by neeasade** [comment]
Oh hello there,

Yes, the panel is broken for perhaps 2 weeks now -- I did not update it on
purpose to give me more incentive to work on it's replacement (
https://github.com/neeasade/lemonade) -- and as for the panel not starting
initially, that is a side effect of a recent re-work of the bspwmrc. You
can still toggle it with panelt or the keybind super + shift + /, I have
not decided how to start it initially yet. I will be taking a more
prioritized look at panel replacement this evening (it's the top item on
meta/README.md)

I appreciate your effort/checking a VM before filing the issue.

Thanks for letting me know,
neeasade

**Comment by neeasade** [comment]
Oh hello there. 

Yes, the panel is broken for perhaps 2 weeks now -- I did not update it on purpose to give me more incentive to work on it's replacement (https://github.com/neeasade/lemonade) -- and as for the panel not starting initially, that is a side effect of a recent re-work of the bspwmrc. You can still toggle it with panelt or the keybind super + shift + /, I have not decided how to start it initially yet. I will be taking a more prioritized look at panel replacement this evening (it's the top item on meta/README.md)

I appreciate your effort/checking a VM before filing the issue. 

Thanks for letting me know,

neeasade

**Comment by CorePoint** [comment]
Hey,

thank you for the insight, maintaining this repository and for all your work.
Now i'm waiting eagerly for your update.

Have a nice day. :)

**Comment by neeasade** [comment]
Sorry, this probably won't be happening until around next sunday evening.

**Comment by CorePoint** [comment]
Thank you, for the status update.

**Comment by neeasade** [comment]
The panel is still incomplete/not fully integrated with themes, but the desktop section is functional again.
