### ISSUE TITLE
Finish your mailblock

### ISSUE THREAD

**Issue by Anachron** [neeasade/dotfiles#12]
https://github.com/neeasade/dotfiles/blob/master/wm/.wm/panel/info.sh#L56-L60

I think you can reuse most of the code that I was writing here:
https://github.com/Anachron/i3blocks/blob/master/blocks/mail

It uses openssl and allows to login to any imap server, so you don't need to install external tools.

**Comment by neeasade** [comment]
Very neat, thanks. Will close this when integrated.

Thanks,
Nathan
