### ISSUE TITLE
Add support for Emacs

### ISSUE THREAD

**Issue by ghost** [neeasade/dotfiles#13]
Suggestions: 
- php-mode (https://github.com/ejmr/php-mode)
  - note, this does not really support templates. That requires minor modes.
- csharp-mode (https://github.com/josteink/csharp-mode)
- whitespace-mode settings
- backspace fixer (windows only?)
  - (global-set-key [(control h)] 'delete-backward-char)
- basic offset settings?
  - (setq c-basic-offset 4)
- no tabs?
  - (setq-default indent-tabs-mode nil)
- automatically accept changes made to file if file not changed in current buffer
  - (global-auto-revert-mode t)
- macros for window resizing
  - quick examples:
    - (global-set-key (vector (list 'shift 'left)) (lambda () (interactive) (shrink-window-horizontally 5)))
    - (global-set-key (vector (list 'shift 'right)) (lambda () (interactive) (enlarge-window-horizontally 5)))
    - (global-set-key (vector (list 'shift 'down)) (lambda () (interactive) (shrink-window 5)))
    - (global-set-key (vector (list 'shift 'up)) (lambda () (interactive) (enlarge-window 5)))

**Comment by neeasade** [comment]
epic, thanks for the tips/links.

gonna dump some links I'd been referencing or planning to reference
- http://blog.aaronbieber.com/2015/05/24/from-vim-to-emacs-in-fourteen-days.html
- https://github.com/alanpearce/dotfiles/blob/master/tag-emacs/emacs.d/init.org
- https://github.com/technomancy/emacs-starter-kit
- http://blog.aaronbieber.com/2016/01/30/dig-into-org-mode.html
- http://nathantypanski.com/blog/2014-07-02-switching-to-emacs.html

edit: http://noctuid.github.io/blog/2015/02/03/a-more-evil-helm/

org mode interests me (haven't used it yet). primary emacs use has not been on personal computer, will add to dots soon™

**Comment by ghost** [comment]
These are what i call quality of life issues, i don't like using emacs much without these.

**Comment by vyp** [comment]
If you're a vim user planning to try evil mode, I'd also like to point you to this section in particular: http://nathantypanski.com/blog/2014-08-03-a-vim-like-emacs-config.html#stealing-ibuffers-keymap. Which gives you a way to integrate evil mode with all the [Special](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Major-Modes.html) modes you may encounter. (I use [use-package](https://github.com/jwiegley/use-package) instead of `eval-after-load` but the idea is the same.)

**Comment by neeasade** [comment]
@niebieskitrociny are you running emacs via cygwin? 

this bit: 

> backspace fixer (windows only?)
>     (global-set-key [(control h)] 'delete-backward-char)

I don't think applies to me (using windows install of emacs, backspace functions as backspace)

edit: this does fix my issue in xst terminal though. hrm

**Comment by vyp** [comment]
Just found https://github.com/noctuid/evil-guide if you haven't already. Again assuming you're using evil mode. Also check out http://spacemacs.org/ btw.
