### ISSUE TITLE
How do i use the double borders bspwm script?

### ISSUE THREAD

**Issue by aimon1337** [neeasade/dotfiles#17]
I know this sounds nubish, but how do i use this script?

**Comment by neeasade** [comment]
install https://github.com/wmutils/opt/

then: 

```
curl "https://raw.githubusercontent.com/neeasade/dotfiles/master/wm/.wm/scripts/visual/2bspwm" >./2bspwm
chmod +x ./2bspwm
./2bspwm
```

Play with the variable values in the script to get differing widths/colors

**Comment by aimon1337** [comment]
> curl "https://raw.githubusercontent.com/neeasade/dotfiles/master/wm/.wm/scripts/visual/2bspwm" >./2bspwm
> chmod +x ./2bspwm
> ./2bspwm

i get this error: `

`./2bspwm: line 7: type: bspwindows : not found`

`

**Comment by fxzzi** [comment]
when I try running it states that bspwindows was not found.
