### ISSUE TITLE
Issue using script with lightdm [Manjaro]

### ISSUE THREAD

**Issue by lordzweigar** [neeasade/dotfiles#3]
The install process works and all is good, however upon  user login sxhkd fails to load. The solution is to open another tty and start. Furthermore, the bar doesn't load right, leaving the bar without slops and some of the items fail to load.

P.S add rofi to the script, its based.

**Comment by neeasade** [comment]
Will try with lightDM and see what's going on - which bar items fail to load?

**Comment by lordzweigar** [comment]
it doesn't load right when started from light dm, however if started from startx it loads correctly

**Comment by neeasade** [comment]
Alright, looked into it today - in the arch wiki there's instructions for migrating from slim if you want to exec everything in xinitrc(where sxhkd is) - added the .xprofile, which fixed this for me(https://github.com/neeasade/dotfiles/commit/8c97771dd2f663e16ad7e22dcecb0612de915d3b).

Let me know if it that fixed it for you.

EDIT: There is a main difference with this I noticed - with the old way(executing .xinitrc) things are launched as if from a bash shell(meaning they take advantage or the .bashrc things like adding panel scripts to path). This can break some of the sxhkd binds, unless full paths are used in calling scripts from them - fixing that.
