### ISSUE TITLE
Feature Request: Github notifications

### ISSUE THREAD

**Issue by ukn-ubi** [neeasade/dotfiles#8]
I'd like to request a Github notifications section/applet in the Lemonbar. Is this possible? I love your config! :smiley:

**Comment by neeasade** [comment]
I like this idea. Perhaps a dzen2 dropdown with current notifications. 

It's definitely possible - wait a week and I'll see where it fits into my [panel rewrite](https://github.com/neeasade/lemonade) by then.

**Comment by neeasade** [comment]
Hm - after thinking this over further and talking with a friend a bit, this would be a bit over the top compared to opening the browser and having it there. The need to have an api key for it makes it seem like overreach for the panel. 

If you wanted to pursue  this in the current layout though some steps:
- get an api key for github 
- read [here](https://developer.github.com/v3/activity/notifications/) for notifications api
- either make a bash script using curl / python script to parse the json and get notifications and count
- add a function to the dzen.sh panel file to handle your scripts
- add a function to the info.sh panel file to display the count/link to notifications. 
- configure your panel to use the info.sh function in ~/.config/bpswm/base_theme.bspwm_theme

I might work on this at some point, but can't promise anything.

**Comment by ukn-ubi** [comment]
Awesome mate! :smile: Tell me if you need any help!

**Comment by ukn-ubi** [comment]
After I restart I will check but I think I got the notification opener part(I used a generic icon) I will continue to work on a thing that gets and displays notifications. Have a good day!

**Comment by ukn-ubi** [comment]
I didn't quite get it right yet. How do I display a new item? I put it in the block.
